import dotenv from "dotenv";
dotenv.config();
import { supabaseAdmin } from "../src/lib/supabaseAdmin.js";

const batch5 = [
  // 1. NIPRO JMI Pharma Ltd(2%) (54 Products)
  {
    name: "Adarbi 40",
    generic_name: "Azilsartan Medoxomil",
    company: "NIPRO JMI Pharma Ltd",
    category_name_fallback: "Cardiovascular",
    strength: "40 mg",
    pack_size: "30 Pcs",
    mrp: 280,
    selling_price: 229.60,
    stock_quantity: 0,
  },
  {
    name: "Altrip 6.25",
    generic_name: "Carvedilol",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "6.25 mg",
    pack_size: "50 Pcs",
    mrp: 250,
    selling_price: 205.80,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Arcet 10",
    generic_name: "Cetirizine Hydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antihistamine",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "30 Pcs",
    mrp: 201,
    selling_price: 154.23,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Avamist 27.5mcg",
    generic_name: "Fluticasone Furoate",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Respiratory",
    dosage_form: "Nasal Spray",
    strength: "27.5 mcg",
    pack_size: "1 Pcs",
    mrp: 275,
    selling_price: 225.31,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Avator 10",
    generic_name: "Atorvastatin Calcium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "30 Pcs",
    mrp: 360,
    selling_price: 298.80,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Avator 20",
    generic_name: "Atorvastatin Calcium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "20 mg",
    pack_size: "20 Pcs",
    mrp: 400,
    selling_price: 337.40,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Azaltic 500",
    generic_name: "Azithromycin",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antibiotic",
    dosage_form: "Tablet",
    strength: "500 mg",
    pack_size: "12 Pcs",
    mrp: 420,
    selling_price: 261.62,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Bilfast 20",
    generic_name: "Bilastine",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antihistamine",
    dosage_form: "Tablet",
    strength: "20 mg",
    pack_size: "30 Pcs",
    mrp: 450,
    selling_price: 386.01,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Bisopress 2.5",
    generic_name: "Bisoprolol Fumarate",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "2.5 mg",
    pack_size: "30 Pcs",
    mrp: 210,
    selling_price: 176.59,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Bisopress 5",
    generic_name: "Bisoprolol Fumarate",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "5 mg",
    pack_size: "30 Pcs",
    mrp: 345,
    selling_price: 293.53,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Calgi D 500",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    pack_size: "30 Pcs",
    mrp: 320,
    selling_price: 249.28,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Calgi DX 600",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "600 mg + 400 IU",
    pack_size: "30 Pcs",
    mrp: 512,
    selling_price: 398.59,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Citrux C 250mg",
    generic_name: "Vitamin C (Ascorbic Acid)",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "250 mg",
    pack_size: "100 Pcs",
    mrp: 190,
    selling_price: 155.59,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Diacana 100",
    generic_name: "Canagliflozin",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "100 mg",
    pack_size: "30 Pcs",
    mrp: 600,
    selling_price: 492.00,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "DIAZID 80",
    generic_name: "Gliclazide",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "80 mg",
    pack_size: "50 Pcs",
    mrp: 350,
    selling_price: 285.01,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Doxiva 400",
    generic_name: "Doxofylline",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Respiratory",
    dosage_form: "Tablet",
    strength: "400 mg",
    pack_size: "50 Pcs",
    mrp: 600,
    selling_price: 511.86,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Doxiva 200",
    generic_name: "Doxofylline",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Respiratory",
    dosage_form: "Tablet",
    strength: "200 mg",
    pack_size: "100 Pcs",
    mrp: 800,
    selling_price: 683.92,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Emjenta 10/5",
    generic_name: "Empagliflozin + Linagliptin",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "10 mg + 5 mg",
    pack_size: "30 Pcs",
    mrp: 1050,
    selling_price: 913.50,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Emjenta 25/5",
    generic_name: "Empagliflozin + Linagliptin",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "25 mg + 5 mg",
    pack_size: "10 Pcs",
    mrp: 500,
    selling_price: 410.00,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Empamet 12.5/500",
    generic_name: "Empagliflozin + Metformin Hydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "12.5 mg + 500 mg",
    pack_size: "28 Pcs",
    mrp: 840,
    selling_price: 688.80,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Empamet 5/500",
    generic_name: "Empagliflozin + Metformin Hydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "5 mg + 500 mg",
    pack_size: "30 Pcs",
    mrp: 600,
    selling_price: 526.20,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "EmpaMet 5/850",
    generic_name: "Empagliflozin + Metformin Hydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "5 mg + 850 mg",
    pack_size: "32 Pcs",
    mrp: 704,
    selling_price: 577.28,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "EmpaMet XR 10/1000",
    generic_name: "Empagliflozin + Metformin Hydrochloride XR",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "10 mg + 1000 mg",
    pack_size: "20 Pcs",
    mrp: 560,
    selling_price: 459.20,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "EmpaMet XR 25/1000",
    generic_name: "Empagliflozin + Metformin Hydrochloride XR",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "25 mg + 1000 mg",
    pack_size: "20 Pcs",
    mrp: 880,
    selling_price: 721.60,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Empamet XR 5/1000",
    generic_name: "Empagliflozin + Metformin Hydrochloride XR",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "5 mg + 1000 mg",
    pack_size: "20 Pcs",
    mrp: 400,
    selling_price: 328.00,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Erdostin 300",
    generic_name: "Erdosteine",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Respiratory",
    dosage_form: "Capsule",
    strength: "300 mg",
    pack_size: "30 Pcs",
    mrp: 480,
    selling_price: 394.37,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Esotor 20 Tab",
    generic_name: "Esomeprazole Magnesium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Tablet",
    strength: "20 mg",
    pack_size: "50 Pcs",
    mrp: 350,
    selling_price: 287.00,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Fenticona 2% Cream",
    generic_name: "Fenticonazole Nitrate",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "2%",
    pack_size: "1 Pcs",
    mrp: 195,
    selling_price: 161.69,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Glucomin 850",
    generic_name: "Metformin Hydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "850 mg",
    pack_size: "50 Pcs",
    mrp: 300,
    selling_price: 246.00,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Irobest 47mg+",
    generic_name: "Carbonyl Iron + Folic Acid + Zinc",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Capsule",
    strength: "47 mg + 0.5 mg + 22.5 mg",
    pack_size: "30 Pcs",
    mrp: 210,
    selling_price: 175.75,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Lijenta 5",
    generic_name: "Linagliptin",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "5 mg",
    pack_size: "30 Pcs",
    mrp: 660,
    selling_price: 572.48,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Lijenta M 1000",
    generic_name: "Linagliptin + Metformin Hydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "2.5 mg + 1000 mg",
    pack_size: "16 Pcs",
    mrp: 256,
    selling_price: 209.92,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Lijenta M 500",
    generic_name: "Linagliptin + Metformin Hydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "2.5 mg + 500 mg",
    pack_size: "60 Pcs",
    mrp: 780,
    selling_price: 683.59,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Lijenta M 850",
    generic_name: "Linagliptin + Metformin Hydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "2.5 mg + 850 mg",
    pack_size: "30 Pcs",
    mrp: 480,
    selling_price: 407.95,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Losarva 50",
    generic_name: "Losartan Potassium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "50 mg",
    pack_size: "50 Pcs",
    mrp: 400,
    selling_price: 328.44,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Losarva Plus 50",
    generic_name: "Losartan Potassium + Hydrochlorothiazide",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "50 mg + 12.5 mg",
    pack_size: "50 Pcs",
    mrp: 500,
    selling_price: 416.80,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Lyrinex Cr 82.5",
    generic_name: "Pregabalin Controlled Release",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Neurology",
    dosage_form: "Tablet",
    strength: "82.5 mg",
    pack_size: "30 Pcs",
    mrp: 540,
    selling_price: 437.78,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Metavas MR 35",
    generic_name: "Trimetazidine Dihydrochloride",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "35 mg",
    pack_size: "60 Pcs",
    mrp: 480,
    selling_price: 395.33,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Montiva 10",
    generic_name: "Montelukast Sodium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Respiratory",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "30 Pcs",
    mrp: 480,
    selling_price: 286.90,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Nimovo 500+20",
    generic_name: "Naproxen Sodium + Esomeprazole Magnesium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Pain Relief",
    dosage_form: "Tablet",
    strength: "500 mg + 20 mg",
    pack_size: "60 Pcs",
    mrp: 600,
    selling_price: 385.32,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Nipro Gold",
    generic_name: "Multivitamin & Multimineral",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "32 Vitamins & Minerals",
    pack_size: "30 Pcs",
    mrp: 300,
    selling_price: 250.80,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Omecron 20",
    generic_name: "Omeprazole",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "20 mg",
    pack_size: "50 Pcs",
    mrp: 250,
    selling_price: 168.50,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Pandura 1",
    generic_name: "Pitavastatin",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "1 mg",
    pack_size: "50 Pcs",
    mrp: 450,
    selling_price: 369.00,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Pandura 2",
    generic_name: "Pitavastatin",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "2 mg",
    pack_size: "30 Pcs",
    mrp: 360,
    selling_price: 295.85,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Rablet 20",
    generic_name: "Rabeprazole Sodium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Tablet",
    strength: "20 mg",
    pack_size: "50 Pcs",
    mrp: 350,
    selling_price: 296.35,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Receca 100",
    generic_name: "Racecadotril",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "100 mg",
    pack_size: "30 Pcs",
    mrp: 240,
    selling_price: 195.53,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Rovator 10",
    generic_name: "Rosuvastatin Calcium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "30 Pcs",
    mrp: 750,
    selling_price: 597.30,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Rovator 5",
    generic_name: "Rosuvastatin Calcium",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "5 mg",
    pack_size: "30 Pcs",
    mrp: 375,
    selling_price: 302.36,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Starcal D 500 mg+200 IU",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    pack_size: "60 Pcs",
    mrp: 480,
    selling_price: 278.88,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Toralin 10",
    generic_name: "Torsemide",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "30 Pcs",
    mrp: 302.1,
    selling_price: 216.15,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "V3N 100mg+200mg+200mcg",
    generic_name: "Vitamin B1 + B6 + B12",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "100 mg + 200 mg + 200 mcg",
    pack_size: "50 Pcs",
    mrp: 500,
    selling_price: 406.00,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Vorifix 200",
    generic_name: "Voriconazole",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antifungal",
    dosage_form: "Tablet",
    strength: "200 mg",
    pack_size: "10 Pcs",
    mrp: 1000,
    selling_price: 820.00,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Xinarox Cv 250",
    generic_name: "Cefuroxime Axetil + Clavulanic Acid",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antibiotic",
    dosage_form: "Tablet",
    strength: "250 mg + 62.5 mg",
    pack_size: "12 Pcs",
    mrp: 420,
    selling_price: 349.90,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Xinarox CV 500",
    generic_name: "Cefuroxime Axetil + Clavulanic Acid",
    manufacturer: "NIPRO JMI Pharma Ltd.",
    category: "Antibiotic",
    dosage_form: "Tablet",
    strength: "500 mg + 125 mg",
    pack_size: "8 Pcs",
    mrp: 440,
    selling_price: 361.02,
    stock_quantity: 100,
    requires_prescription: true,
  },

  // 2. Navana Pharmaceuticals Ltd.(2%) (50 Products)
  {
    name: "Allertin 20",
    generic_name: "Bilastine",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antihistamine",
    dosage_form: "Tablet",
    strength: "20 mg",
    pack_size: "30 Pcs",
    mrp: 450,
    selling_price: 357.84,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Arokast 10",
    generic_name: "Montelukast Sodium",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Respiratory",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "30 Pcs",
    mrp: 480,
    selling_price: 361.34,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Artiforte 10 ml",
    generic_name: "Hydroxypropyl Methylcellulose + Dextran",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.3% + 0.1%",
    pack_size: "1 Pcs",
    mrp: 275,
    selling_price: 225.50,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Azirox 500",
    generic_name: "Azithromycin",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antibiotic",
    dosage_form: "Tablet",
    strength: "500 mg",
    pack_size: "18 Pcs",
    mrp: 632,
    selling_price: 459.91,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Cfresh Liquigel 1%",
    generic_name: "Carboxymethylcellulose Sodium",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "1%",
    pack_size: "1 Pcs",
    mrp: 300,
    selling_price: 201.90,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Cinagen 0.5% 5 ml",
    generic_name: "Moxifloxacin Hydrochloride",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.5%",
    pack_size: "1 Pcs",
    mrp: 160,
    selling_price: 110.22,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Cinagen D 5 ml",
    generic_name: "Moxifloxacin + Dexamethasone",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.5% + 0.1%",
    pack_size: "1 Pcs",
    mrp: 250,
    selling_price: 175.35,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Clascon 10",
    generic_name: "Clascoterone",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "10 mg",
    pack_size: "1 Box",
    mrp: 900,
    selling_price: 738.00,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Conpan 0.5",
    generic_name: "Clonazepam",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Neurology",
    dosage_form: "Tablet",
    strength: "0.5 mg",
    pack_size: "50 Pcs",
    mrp: 330,
    selling_price: 244.89,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Curafin 0.25% (30 gm Tube)",
    generic_name: "Amorolfine",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "0.25%",
    pack_size: "30 gm Tube",
    mrp: 280,
    selling_price: 220.39,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Dextac 30 (Mrp 1000)",
    generic_name: "Dexlansoprazole",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "30 mg",
    pack_size: "100 Pcs",
    mrp: 1000,
    selling_price: 762.00,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Dextac 30 (Mrp 600)",
    generic_name: "Dexlansoprazole",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "30 mg",
    pack_size: "60 pcs",
    mrp: 600,
    selling_price: 462.12,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Diplin 5",
    generic_name: "Linagliptin",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "5 mg",
    pack_size: "30 Pcs",
    mrp: 660,
    selling_price: 526.09,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Diplin M 500",
    generic_name: "Linagliptin + Metformin Hydrochloride",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "2.5 mg + 500 mg",
    pack_size: "30 Pcs",
    mrp: 360,
    selling_price: 275.65,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Duracef 200",
    generic_name: "Cefixime",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antibiotic",
    dosage_form: "Capsule",
    strength: "200 mg",
    pack_size: "12 Pcs",
    mrp: 420,
    selling_price: 314.16,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Duracef 400",
    generic_name: "Cefixime",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antibiotic",
    dosage_form: "Capsule",
    strength: "400 mg",
    pack_size: "12 Pcs",
    mrp: 660,
    selling_price: 493.42,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Esona 500/20",
    generic_name: "Naproxen Sodium + Esomeprazole Magnesium",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Pain Relief",
    dosage_form: "Tablet",
    strength: "500 mg + 20 mg",
    pack_size: "50 Pcs",
    mrp: 667,
    selling_price: 522.60,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Esotac 20",
    generic_name: "Esomeprazole Magnesium",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "20 mg",
    pack_size: "60 Pcs",
    mrp: 420,
    selling_price: 290.22,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Itracon 100",
    generic_name: "Itraconazole",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antifungal",
    dosage_form: "Capsule",
    strength: "100 mg",
    pack_size: "30 pcs",
    mrp: 510,
    selling_price: 392.19,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Itracon 200",
    generic_name: "Itraconazole",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antifungal",
    dosage_form: "Tablet",
    strength: "200 mg",
    pack_size: "30 Pcs",
    mrp: 900,
    selling_price: 681.21,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Itracon Suba (MRP 1200)",
    generic_name: "Itraconazole Submicronized",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antifungal",
    dosage_form: "Capsule",
    strength: "50 mg",
    pack_size: "60 Pcs",
    mrp: 1200,
    selling_price: 928.80,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Joytrip 150 (Mrp 481.92)",
    generic_name: "Meclizine Hydrochloride + Pyridoxine Hydrochloride",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antiemetic",
    dosage_form: "Tablet",
    strength: "150 mcg",
    pack_size: "12 Pcs",
    mrp: 481.92,
    selling_price: 360.14,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Joytrip 300",
    generic_name: "Meclizine Hydrochloride + Pyridoxine Hydrochloride",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antiemetic",
    dosage_form: "Tablet",
    strength: "300 mcg",
    pack_size: "12 Pcs",
    mrp: 960,
    selling_price: 716.93,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Kindical D (Mrp 575)",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    pack_size: "50 Pcs",
    mrp: 575,
    selling_price: 471.50,
    stock_quantity: 0,
    requires_prescription: false,
  },
  {
    name: "Kindical DX 600mg",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "600 mg + 400 IU",
    pack_size: "30 pcs",
    mrp: 480,
    selling_price: 364.80,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "L-Amlo 5",
    generic_name: "Levamlodipine",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "5 mg",
    pack_size: "30 Pcs",
    mrp: 270,
    selling_price: 230.85,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Lipostat 10",
    generic_name: "Atorvastatin Calcium",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "30pcs",
    mrp: 300,
    selling_price: 216.21,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Loteba 5 ml",
    generic_name: "Loteprednol Etabonate",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.5%",
    pack_size: "1 Pcs",
    mrp: 200,
    selling_price: 133.66,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Loxodol 4",
    generic_name: "Lornoxicam",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Pain Relief",
    dosage_form: "Tablet",
    strength: "4 mg",
    pack_size: "30 Pcs",
    mrp: 300,
    selling_price: 231.00,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Lulider 10 10 gm",
    generic_name: "Luliconazole",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "1%",
    pack_size: "1 Pcs",
    mrp: 100,
    selling_price: 82.19,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Lulider 30",
    generic_name: "Luliconazole",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "1%",
    pack_size: "1 tube",
    mrp: 280,
    selling_price: 210.95,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Malifa 30 (Mrp 660)",
    generic_name: "Ferric Maltol",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Supplement",
    dosage_form: "Capsule",
    strength: "30 mg",
    pack_size: "60 Pcs",
    mrp: 660,
    selling_price: 507.14,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "N Bion 100 mg+200 mg+200 mcg",
    generic_name: "Vitamin B1 + B6 + B12",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "100 mg + 200 mg + 200 mcg",
    pack_size: "60 Pcs",
    mrp: 600,
    selling_price: 469.02,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Nabuton 750",
    generic_name: "Nabumetone",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Pain Relief",
    dosage_form: "Tablet",
    strength: "750 mg",
    pack_size: "24 Pcs",
    mrp: 528,
    selling_price: 432.96,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Nafgal Cream 30gm",
    generic_name: "Naftifine Hydrochloride",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "1%",
    pack_size: "30 gm tube",
    mrp: 230,
    selling_price: 185.84,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Navacef 125 15 ml",
    generic_name: "Cefixime",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Antibiotic",
    dosage_form: "Paediatric Drops",
    strength: "125 mg / 1.25 ml",
    pack_size: "1 Pcs",
    mrp: 135,
    selling_price: 112.43,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Neparact TS 3 ml",
    generic_name: "Nepafenac",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.3%",
    pack_size: "1 Pcs",
    mrp: 145,
    selling_price: 118.90,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Nestor 10",
    generic_name: "Rosuvastatin Calcium",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "20 Pcs",
    mrp: 401.2,
    selling_price: 275.91,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Nortin 25",
    generic_name: "Nortriptyline Hydrochloride",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Neurology",
    dosage_form: "Capsule",
    strength: "25 mg",
    pack_size: "100 Pcs",
    mrp: 400,
    selling_price: 302.56,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Ometac 20 (Navana)",
    generic_name: "Omeprazole",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "20 mg",
    pack_size: "100 pcs",
    mrp: 500,
    selling_price: 283.90,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Phoscon 210 mg",
    generic_name: "Ferric Citrate",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "210 mg",
    pack_size: "30 pcs",
    mrp: 750,
    selling_price: 598.95,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Pizofen 0.5",
    generic_name: "Pizotifen Malate",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Neurology",
    dosage_form: "Tablet",
    strength: "0.5 mg",
    pack_size: "100 Pcs",
    mrp: 301,
    selling_price: 241.10,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Pizofen TS 1.5mg",
    generic_name: "Pizotifen Malate",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Neurology",
    dosage_form: "Tablet",
    strength: "1.5 mg",
    pack_size: "50 Pcs",
    mrp: 351,
    selling_price: 287.82,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Pmec Cream 1%",
    generic_name: "Permethrin",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "1%",
    pack_size: "1 Pcs",
    mrp: 1000,
    selling_price: 817.70,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Pregan Er 82.5",
    generic_name: "Pregabalin Extended Release",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Neurology",
    dosage_form: "Tablet",
    strength: "82.5 mg",
    pack_size: "30 Pcs",
    mrp: 750,
    selling_price: 619.05,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Stedex-C 5 ml",
    generic_name: "Ciprofloxacin + Dexamethasone",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Eye Care",
    dosage_form: "Eye/Ear Drops",
    strength: "0.3% + 0.1%",
    pack_size: "1 Pcs",
    mrp: 70.21,
    selling_price: 49.95,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Sulderm 15gm Cream",
    generic_name: "Silver Sulfadiazine",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "1%",
    pack_size: "15 gm tube",
    mrp: 170,
    selling_price: 139.40,
    stock_quantity: 0,
    requires_prescription: true,
  },
  {
    name: "Sulderm 30 30 gm",
    generic_name: "Silver Sulfadiazine",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "1%",
    pack_size: "1 Box",
    mrp: 300,
    selling_price: 251.07,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Tabis 5",
    generic_name: "Bisoprolol Fumarate",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Cardiovascular",
    dosage_form: "Tablet",
    strength: "5 mg",
    pack_size: "30 Pcs",
    mrp: 300.9,
    selling_price: 232.47,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Vomitop 10mg",
    generic_name: "Domperidone Maleate",
    manufacturer: "Navana Pharmaceuticals Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Tablet",
    strength: "10 mg",
    pack_size: "100 pcs",
    mrp: 320,
    selling_price: 166.98,
    stock_quantity: 100,
    requires_prescription: false,
  },

  // 3. Novartis (Bangladesh) Limited (2 Products)
  {
    name: "Galvus Met 50/500",
    generic_name: "Vildagliptin + Metformin Hydrochloride",
    manufacturer: "Novartis (Bangladesh) Limited",
    category: "Antidiabetic",
    dosage_form: "Tablet",
    strength: "50 mg + 500 mg",
    pack_size: "30 Pcs",
    mrp: 990,
    selling_price: 898.33,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Voltalin 50mg",
    generic_name: "Diclofenac Sodium",
    manufacturer: "Novartis (Bangladesh) Limited",
    category: "Pain Relief",
    dosage_form: "Suppository",
    strength: "50 mg",
    pack_size: "20 pcs",
    mrp: 1200,
    selling_price: 1091.76,
    stock_quantity: 100,
    requires_prescription: true,
  },

  // 4. Novatek Pharmaceuticals Ltd(3%) (6 Products)
  {
    name: "Dexnova 30",
    generic_name: "Dexlansoprazole",
    manufacturer: "Novatek Pharmaceuticals Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "30 mg",
    pack_size: "30 pcs",
    mrp: 300,
    selling_price: 167.01,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Esogel 40",
    generic_name: "Esomeprazole Magnesium",
    manufacturer: "Novatek Pharmaceuticals Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "40 mg",
    pack_size: "50 Pcs",
    mrp: 450,
    selling_price: 185.76,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Melanxit 0.5 mg+10 mg",
    generic_name: "Flupentixol + Melitracen",
    manufacturer: "Novatek Pharmaceuticals Ltd.",
    category: "Psychiatry",
    dosage_form: "Tablet",
    strength: "0.5 mg + 10 mg",
    pack_size: "60 Pcs",
    mrp: 300,
    selling_price: 176.67,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Orgabion",
    generic_name: "Vitamin B Complex",
    manufacturer: "Novatek Pharmaceuticals Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "Vitamin B1 + B6 + B12",
    pack_size: "50 Pcs",
    mrp: 400,
    selling_price: 197.88,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Oscoral D 500 mg+200 IU",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "Novatek Pharmaceuticals Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    pack_size: "30 Pcs",
    mrp: 300,
    selling_price: 182.55,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Oscoral DX 600 mg+400 IU",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "Novatek Pharmaceuticals Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "600 mg + 400 IU",
    pack_size: "30 Pcs",
    mrp: 450,
    selling_price: 237.83,
    stock_quantity: 100,
    requires_prescription: false,
  },

  // 5. Nuvista Pharma Limited (9 Products)
  {
    name: "Lynes 0.05 mg+2.5 mg",
    generic_name: "Ethinylestradiol + Lynestrenol",
    manufacturer: "Nuvista Pharma Limited",
    category: "Women's Health",
    dosage_form: "Tablet",
    strength: "0.05 mg + 2.5 mg",
    pack_size: "22 Pcs",
    mrp: 143,
    selling_price: 127.60,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Marvelon 0.03 mg+0.15 mg",
    generic_name: "Ethinylestradiol + Desogestrel",
    manufacturer: "Nuvista Pharma Limited",
    category: "Women's Health",
    dosage_form: "Tablet",
    strength: "0.03 mg + 0.15 mg",
    pack_size: "21 Pcs",
    mrp: 105,
    selling_price: 93.30,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Nuliza 1% 30 gm",
    generic_name: "Luliconazole",
    manufacturer: "Nuvista Pharma Limited",
    category: "Dermatology",
    dosage_form: "Cream",
    strength: "1%",
    pack_size: "1 Pcs",
    mrp: 280,
    selling_price: 245.00,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Nuprazol 20mg",
    generic_name: "Omeprazole",
    manufacturer: "Nuvista Pharma Limited",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "20 mg",
    pack_size: "50 Pcs",
    mrp: 250,
    selling_price: 212.40,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Oradexon 0.5",
    generic_name: "Dexamethasone",
    manufacturer: "Nuvista Pharma Limited",
    category: "Corticosteroid",
    dosage_form: "Tablet",
    strength: "0.5 mg",
    pack_size: "500 Pcs",
    mrp: 575,
    selling_price: 504.33,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Thyronor 25",
    generic_name: "Levothyroxine Sodium",
    manufacturer: "Nuvista Pharma Limited",
    category: "Endocrinology",
    dosage_form: "Tablet",
    strength: "25 mcg",
    pack_size: "105 Pcs",
    mrp: 116.55,
    selling_price: 102.18,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Thyronor 50",
    generic_name: "Levothyroxine Sodium",
    manufacturer: "Nuvista Pharma Limited",
    category: "Endocrinology",
    dosage_form: "Tablet",
    strength: "50 mcg",
    pack_size: "105 Pcs",
    mrp: 239.4,
    selling_price: 213.45,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Traxyl 500",
    generic_name: "Tranexamic Acid",
    manufacturer: "Nuvista Pharma Limited",
    category: "Haemostatic",
    dosage_form: "Capsule",
    strength: "500 mg",
    pack_size: "30 Pcs",
    mrp: 750,
    selling_price: 646.35,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Visceralgine 50",
    generic_name: "Tiemonium Methylsulfate",
    manufacturer: "Nuvista Pharma Limited",
    category: "Antispasmodic",
    dosage_form: "Tablet",
    strength: "50 mg",
    pack_size: "60 Pcs",
    mrp: 540,
    selling_price: 466.18,
    stock_quantity: 100,
    requires_prescription: true,
  },

  // 6. OSL Pharma LTD(4%) (22 Products)
  {
    name: "Aqua 10 (Opso Saline)",
    generic_name: "Carboxymethylcellulose Sodium",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.5%",
    pack_size: "1 Box",
    mrp: 200,
    selling_price: 149.96,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Bakticef 500 Inj",
    generic_name: "Ceftriaxone Sodium",
    manufacturer: "Opso Saline Ltd.",
    category: "Antibiotic",
    dosage_form: "IM Injection",
    strength: "500 mg",
    pack_size: "1 Box",
    mrp: 155,
    selling_price: 66.12,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Clacef 250 (OSL)",
    generic_name: "Cefuroxime Axetil + Clavulanic Acid",
    manufacturer: "Opso Saline Ltd.",
    category: "Antibiotic",
    dosage_form: "Tablet",
    strength: "250 mg + 62.5 mg",
    pack_size: "16 pcs",
    mrp: 560,
    selling_price: 393.34,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Clacef 500 (OSL)",
    generic_name: "Cefuroxime Axetil + Clavulanic Acid",
    manufacturer: "Opso Saline Ltd.",
    category: "Antibiotic",
    dosage_form: "Tablet",
    strength: "500 mg + 125 mg",
    pack_size: "12 pcs",
    mrp: 660,
    selling_price: 463.91,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Corcal D 500 mg+200 IU (OSL)",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "Opso Saline Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    pack_size: "30 Pcs",
    mrp: 330,
    selling_price: 227.96,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Corcal DX 600 mg+400 IU (OSL)",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "Opso Saline Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "600 mg + 400 IU",
    pack_size: "30 Pcs",
    mrp: 480,
    selling_price: 334.66,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Dewgel Liquigel 1%",
    generic_name: "Carboxymethylcellulose Sodium",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "1%",
    pack_size: "1 Pcs",
    mrp: 275,
    selling_price: 181.58,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Exilok 20",
    generic_name: "Esomeprazole Magnesium",
    manufacturer: "Opso Saline Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "20 mg",
    pack_size: "90 Pcs",
    mrp: 630,
    selling_price: 332.07,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Eyefresh 10 ml",
    generic_name: "Carboxymethylcellulose Sodium",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.5%",
    pack_size: "1 Pcs",
    mrp: 80,
    selling_price: 62.36,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Flomox 0.5% Eye Drop",
    generic_name: "Moxifloxacin Hydrochloride",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.5%",
    pack_size: "5 ml drop",
    mrp: 140,
    selling_price: 95.40,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Floxabac 500",
    generic_name: "Flucloxacillin Sodium",
    manufacturer: "Opso Saline Ltd.",
    category: "Antibiotic",
    dosage_form: "Capsule",
    strength: "500 mg",
    pack_size: "28 Pcs",
    mrp: 294,
    selling_price: 221.62,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Gatidex 0.3%+0.1%",
    generic_name: "Gatifloxacin + Dexamethasone",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.3% + 0.1%",
    pack_size: "5 ml drop",
    mrp: 120.37,
    selling_price: 85.57,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Lubrigel 0.4%+0.3%",
    generic_name: "Polyethylene Glycol + Propylene Glycol",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.4% + 0.3%",
    pack_size: "10 ml drop",
    mrp: 200,
    selling_price: 139.96,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Norsol 0.9% 10ml",
    generic_name: "Sodium Chloride",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drops",
    strength: "0.9%",
    pack_size: "14 pcs",
    mrp: 322,
    selling_price: 251.80,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Nutrifil Gold",
    generic_name: "Multivitamin & Multimineral",
    manufacturer: "Opso Saline Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "32 Vitamins & Minerals",
    pack_size: "30 Pcs",
    mrp: 300,
    selling_price: 207.12,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Olofix Ds 0.2% 5 ml",
    generic_name: "Olopatadine Hydrochloride",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.2%",
    pack_size: "1 Pcs",
    mrp: 180,
    selling_price: 122.98,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Opsocrom 10 ml",
    generic_name: "Sodium Cromoglicate",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "2%",
    pack_size: "1 Pcs",
    mrp: 65.19,
    selling_price: 47.70,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Opsophenicol 10ml",
    generic_name: "Chloramphenicol",
    manufacturer: "Opso Saline Ltd.",
    category: "Eye Care",
    dosage_form: "Eye Drop",
    strength: "0.5%",
    pack_size: "14 Pcs",
    mrp: 483,
    selling_price: 354.38,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Sucofer 5 5 ml",
    generic_name: "Iron Sucrose",
    manufacturer: "Opso Saline Ltd.",
    category: "Haematinic",
    dosage_form: "IV Infusion",
    strength: "20 mg/ml",
    pack_size: "1 Pcs",
    mrp: 350,
    selling_price: 182.53,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Unibac 200",
    generic_name: "Cefixime",
    manufacturer: "Opso Saline Ltd.",
    category: "Antibiotic",
    dosage_form: "Capsule",
    strength: "200 mg",
    pack_size: "14 Pcs",
    mrp: 560,
    selling_price: 328.83,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Xanra 30",
    generic_name: "Dexlansoprazole",
    manufacturer: "Opso Saline Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "30 mg",
    pack_size: "50 Pcs",
    mrp: 450,
    selling_price: 315.86,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Zixin 500",
    generic_name: "Azithromycin",
    manufacturer: "Opso Saline Ltd.",
    category: "Antibiotic",
    dosage_form: "Tablet",
    strength: "500 mg",
    pack_size: "7 Pcs",
    mrp: 315,
    selling_price: 244.22,
    stock_quantity: 100,
    requires_prescription: true,
  },

  // 7. One Pharma Ltd(3%) (3 Products)
  {
    name: "Onedex 30",
    generic_name: "Dexlansoprazole",
    manufacturer: "One Pharma Ltd.",
    category: "Gastrointestinal",
    dosage_form: "Capsule",
    strength: "30 mg",
    pack_size: "60 Pcs",
    mrp: 600,
    selling_price: 412.62,
    stock_quantity: 100,
    requires_prescription: true,
  },
  {
    name: "Xelcoral D 500 mg+200 IU",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "One Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    pack_size: "30 Pcs",
    mrp: 330,
    selling_price: 213.84,
    stock_quantity: 100,
    requires_prescription: false,
  },
  {
    name: "Xelcoral DX 600+400",
    generic_name: "Calcium Carbonate + Vitamin D3",
    manufacturer: "One Pharma Ltd.",
    category: "Supplement",
    dosage_form: "Tablet",
    strength: "600 mg + 400 IU",
    pack_size: "30 Pcs",
    mrp: 480,
    selling_price: 325.78,
    stock_quantity: 100,
    requires_prescription: false,
  },
];

async function syncBatchFive() {
  console.log(`Syncing ${batch5.length} items for NIPRO JMI, Navana, Novartis, Novatek, Nuvista, OSL, and One Pharma...`);
  let count = 0;
  for (const item of batch5) {
    const { data: existing } = await supabaseAdmin
      .from("products")
      .select("id")
      .ilike("name", item.name)
      .limit(1);

    const productPayload: any = {
      name: item.name,
      generic_name: item.generic_name,
      strength: item.strength,
      pack_size: item.pack_size,
      category_name_fallback: item.category || (item as any).category_name_fallback || "General",
      mrp: item.mrp,
      selling_price: item.selling_price,
      company: item.manufacturer || (item as any).company || "General",
      stock_quantity: item.stock_quantity
    };

    if (existing && existing.length > 0) {
      const id = existing[0].id;
      await supabaseAdmin.from("products").update(productPayload).eq("id", id);
      await supabaseAdmin.from("inventory").upsert({
        product_id: id,
        available_stock: item.stock_quantity,
        expiry_date: "2027-12-31"
      }, { onConflict: "product_id" });
      count++;
    } else {
      const { data: inserted, error: insErr } = await supabaseAdmin.from("products").insert(productPayload).select("id").single();
      if (inserted) {
        await supabaseAdmin.from("inventory").insert({
          product_id: inserted.id,
          available_stock: item.stock_quantity,
          reserved_stock: 0,
          sold_stock: 0,
          batch_number: `B-${Math.floor(10000 + Math.random() * 90000)}`,
          expiry_date: "2027-12-31"
        });
        count++;
      } else if (insErr) {
        console.error(`Error inserting ${item.name}:`, insErr.message);
      }
    }
  }
  console.log(`Batch 5 sync successful! Total ${count} products synced.`);
}

syncBatchFive().catch(console.error);

